### ISSUE TITLE
Plugin no longer resolves variables in file fragments in serverless@2.26.0.

### ISSUE THREAD

**Issue by nealshail** [aronim/serverless-plugin-colocate#5]
variables such as  ${self:provider.stage} are no longer resolved in the resulting output file deployed to CloudFormation

see [this pull request](https://github.com/aronim/serverless-plugin-colocate/pull/4)

**Comment by kevinsewell** [comment]
Thank you for the PR. I have merged and released as version 0.0.11

**Comment by nealshail** [comment]
Thanks Kev! that's very helpful for me!
